version: '3.8'

services:
  user_microservice:
    build: ./UserMicro
    command: uvicorn main:app --host=0.0.0.0 --port=5001
    expose:
      - 5001
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - user_microservice
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi
